louisedamal/wetpnp

- app/controllers/pools_controller.rb
- app/models/pool.rb
- app/views/pools/edit.html.erb
- app/views/pools/new.html.erb
- db/migrate/20181127152556_add_city_to_pools.rb
- db/schema.rb
> add city to pools

- app/controllers/bookings_controller.rb
- app/controllers/pools_controller.rb
- app/policies/booking_policy.rb
- app/views/pages/home.html.erb
- test/policies/booking_policy_test.rb
fixed some bugs on index and added pundit on Booking controller
> Debug views

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pools/show.html.erb
- app/views/shared/_navbar.html.erb
> Front pool show

- app/views/pools/show.html.erb
modified:   app/views/pools/show.html.erb
J'ai supprimé les liens "éditer / supprimer" pour les users non autorisés.
+ ajouté le lien vers la réservation sur l'action du clic button
> use policy with an instance

- app/assets/stylesheets/components/_bookinglist.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_tabs.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
- app/views/bookings/show.hmtl.erb
- app/views/bookings/show.html.erb
- config/routes.rb
rajout du dashboard bookings quand on book !
> bookings dashboard

- app/models/pool.rb
- app/views/pools/edit.html.erb
- app/views/pools/new.html.erb
- db/migrate/20181128093743_remove_city_from_pools.rb
- db/schema.rb
City removed from pools, fixed "Create" and "Edit" forms.
Deleted Validation for City.
> City removed done

- app/views/pages/home.html.erb
> deleted City from HomePage

- app/assets/stylesheets/config/_utilities.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- config/locales/simple_form.en.yml
added style in "utilities_css" for further details to pimp
generated Devise "Views" and customized them.
Dirty style ^^ : changed "simple form" default params without using the gem "devise-i18n"
(more info here if you like https://github.com/tigrish/devise-i18n)
Everything works, that's it for the moment, opened to any changes soon or later. :))
> customized style with Devise

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_infowindow.scss
- app/views/pages/_infowindow.html.erb
> infowindow design

- app/views/shared/_navbar.html.erb
> Ajout du lien mes piscines dans la navbar

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/views/pools/show.html.erb
Les cards sont dans un container
le prix est sur la card booking
les icons sont cliquables (edit & delete)
et des font awesome sont rajoutés
> La show de pool est prête

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
> homepage centered

- app/assets/stylesheets/components/_button.scss
- app/views/pages/home.html.erb
only the homepage button is larger
> button fixed

- app/views/pages/_infowindow.html.erb
you can click on the infowindow and have access to the pool's page 
check-it out : 
http://recordit.co/ovlg6qxdVv
> clickable infowindow

- app/assets/stylesheets/components/_form.scss
- app/javascript/components/init_autocomplete.js
- app/views/pages/home.html.erb
- app/views/pools/edit.html.erb
- app/views/pools/new.html.erb
> Ajout de l'autocomplete sur home et edit

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/bookings_controller.rb
- app/controllers/pools_controller.rb
- app/views/shared/_navbar.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
a bit of front for the profile, still not beautiful.. but functionnal
> profile css

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/pools_controller.rb
- app/views/pages/home.html.erb
- app/views/pools/show.html.erb
Simple review displaying on the pool show.
> added reviews on pool show

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_navbar.scss
BG color on cards changed to white, added avatar pix border.
> color adjustment on card BG and Avatar

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/pools/search.html.erb
La search bar de la home est bien 
Rajout d'un "Localiser les piscines" au dessus de la carte
Problème couleur lien navbar home réglé
Réagencement des cards de la home OK
Sur chaque card : /jour pour le prix
Changement des deux polices (si vous en voulez vraiment d'autres trouvez les et envoyer les moi)
>  Fix quelques trucs

- app/assets/stylesheets/components/_autocomplete.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
Map fix dans les recherches 
resultats de recherches noir
> Fix map et search bar black

- app/assets/stylesheets/components/_images.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_poolslist.scss
- app/views/pools/index.html.erb
> show mes piscines

- app/assets/stylesheets/config/_utilities.scss
- app/javascript/components/ratings.js
- app/javascript/packs/application.js
- app/views/pools/show.html.erb
- app/views/reviews/new.html.erb
Added Star ratings and hover options with HTML/CSS/JS files and components.
> rating with golden stars FTW
